name: Set version

on:
  # Triggers the workflow on push to master branch
  push:
    branches: [ master ]


jobs:
  set_version:
    name: Set and tag version
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set version
      id: set_version
      run: |
        LATEST_TAG=`git describe --tags | tr -d '\r' | cut -d'-' -f1`
        MAJOR=`echo $LATEST_TAG | cut -d'.' -f1`
        MINOR=`echo $LATEST_TAG | cut -d'.' -f2`
        PATCH=`echo $LATEST_TAG | cut -d'.' -f3`
        INCREMENTED=$((PATCH+1))
        echo "VERSION=$MAJOR.$MINOR.$INCREMENTED" >> $GITHUB_ENV
    - name: Tag new version
      run: git tag ${{ env.VERSION }}

    - name: Push tags
      uses: ad-m/github-push-action@master
      with:
        tags: true
